// mon-projet-vue/src/App.vue
<script setup>
import {ref, onMounted, computed} from 'vue'

const titre = ref('')
const contenu = ref('')
const message = ref('')
const posts = ref([])

async function envoyerPost() {
    const post = {
        title: titre.value,
        body: contenu.value
    }

    try {
        const reponse = await fetch('https://jsonplaceholder.typicode.com/posts', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(post)
        })
        if (reponse.ok) {
            message.value= " Post envoye avec succes !"

            posts.value.push(post)
            titre.value= ''
            contenu.value= ''
           
        }
        else {
            message.value= "Erreur lors de l'envoie"
        }
    }
    catch (erreur) {
        console.error("Erreur: ", erreur)
    }
}

async function recupererPost(){
    try {
        const result = await fetch('https://jsonplaceholder.typicode.com/posts')
        const donnees = await result.json()
        posts.value = donnees


    } catch(erreur){
        console.error("Erreur lors de la recuperation des postes", erreur)
    }
}

onMounted(() => {
    recupererPost()
})

</script>

<template>
    <h2>Creer un poste</h2>
    <br>
    <label><input v-model="titre" placeholder="Veuillez selectionner un titre"></label>
    <br></br>

    <label><textarea v-model="contenu" placeholder="Veuillez entrer les contenus"></textarea></label>
    <br>
    <br>

    <button @click="envoyerPost">Enregistrer</button>
    <br>
    <h3>
        {{ message }}
    </h3>
        <br>
        <ul>
            <li v-for="post in posts" :key="post.title">
                {{ post.title }} - {{ post.body }}
            </li>        
        </ul>



</template>

// REACT-JS/mon-projet-react/src/App.jsx
import {useState, useEffect} from 'react'

function App(){
    const[posts, setPosts] = useState([])
    const [titre, setTitre] = useState('')

    useEffect(() => {
        fetch(`https://jsonplaceholder.typicode.com/posts?_limit=5`)
        .then(res => res.json())
        .then(data => setPosts(data))
    }, [])


    const ajouterTache = async () => {
        const nouvelleTache ={
            title: titre
        }

        const response = await fetch('https://jsonplaceholder.typicode.com/posts', {
            method: 'POST',
            headers : {'Content-Type': 'application/json'},
            body: JSON.stringify(nouvelleTache)
        })

        if(response.ok) {
            const nouvelObjet = await response.json()
            setPosts([...posts, nouvelObjet])
            setTitre('')
        }
    }

    const supprimerTache = async (id) => {
        const response = await fetch(`https://jsonplaceholder.typicode.com/posts/${id}`, {
            method: 'DELETE'
        })

        if(response.ok) {
            const nouvelleListe = posts.filter((u) => u.id !== id)
            setPosts(nouvelleListe)
        }
    } 

    return (
        <div>
            <input
             type="text"
             value={titre}
             onChange= {(e) => setTitre(e.target.value)} 
             />

             <button onClick={ajouterTache}>
                Ajouter
             </button>
            <ul>
                {posts.map((post) => 
                <li key={post.id}>
                    {post.title}
                    <button onClick={() => supprimerTache(post.id)}>Supprimer</button>
                </li>
            )}
            </ul>
        </div>
    )
}

export default App
